# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-14 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restfultvshows_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shows',
            new_name='Show',
        ),
    ]
