# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-15 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restfultvshows_app', '0002_auto_20191014_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateField(),
        ),
    ]
