# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-18 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='endDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='startDate',
            field=models.DateTimeField(null=True),
        ),
    ]
