# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-22 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20191022_1629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trip',
            new_name='Job',
        ),
    ]
