# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-22 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20191022_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.TextField(null=True),
        ),
    ]
