# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-18 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='uploaded_by_id',
        ),
        migrations.AddField(
            model_name='trip',
            name='plan',
            field=models.TextField(null=True),
        ),
    ]
